Repository ansible-community/molecule-azure, pull requests merged in 2019-10, with the labels that each got.

#5 Bring CI back to green status
  conftest.py
  molecule_azure/driver.py
  molecule_azure/test/__init__.py
  molecule_azure/test/functional/.ansible-lint
  molecule_azure/test/functional/__init__.py
  molecule_azure/test/functional/conftest.py
  molecule_azure/test/functional/test_azure.py
  molecule_azure/test/scenarios/driver/azure/molecule/default/molecule.yml
  molecule_azure/test/scenarios/driver/azure/molecule/default/playbook.yml
  molecule_azure/test/scenarios/driver/azure/molecule/default/tests/test_default.py
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/molecule.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/playbook.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/prepare.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/tests/__init__.py
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/tests/test_default.py
  molecule_azure/test/test_driver.py
  pytest.ini
  setup.cfg
  setup.py
  test/conftest.py
  test/test_driver.py
  tox.ini
Labels: bug

#7 Added configs for github actions.
  .github/labels.yml
  .github/release-drafter.yml
  .yamllint
Labels: test

#3 Release all resources on destroy
  molecule_azure/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
Labels: bug

#9 travis: config refresh
  .travis.yml
Labels: enhancement, test

#10 travis: correct tag matching pattern
  .travis.yml
Labels: packaging, test

#12 Fixed missing template_dir method
  molecule_azure/driver.py
Labels: bug

#11 tox: various fixes
  tox.ini
Labels: skip-changelog, test

#14 Use azure dependencies declared by Ansible
  molecule_azure/driver.py
  setup.cfg
Labels: bug

#16 Fixed functional testing
  .travis.yml
  molecule_azure/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule_azure/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule_azure/test/functional/conftest.py
  molecule_azure/test/functional/test_azure.py
  molecule_azure/test/scenarios/driver/azure/molecule/default/molecule.yml
  molecule_azure/test/scenarios/driver/azure/molecule/default/playbook.yml
  molecule_azure/test/scenarios/driver/azure/molecule/default/tests/test_default.py
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/molecule.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/playbook.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/prepare.yml
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/tests/__init__.py
  molecule_azure/test/scenarios/driver/azure/molecule/multi-node/tests/test_default.py
  pytest.ini
Labels: bug, test
