Repository ansible-community/molecule-azure, pull requests merged in 2020-10, with the labels that each got.

#29 Made dependencies compatible with newer molecule
  setup.cfg
Labels: bug

#30 Added release drafter action
  .github/workflows/release-drafter.yml
Labels: enhancement

#31 Make driver require molecule 3.2
  .github/workflows/tox.yml
  molecule_azure/test/functional/test_azure.py
  setup.cfg
  tox.ini
Labels: major

#23 Rely on resource group removal when performing destroy
  molecule_azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule_azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
Labels: enhancement
